services:
  bot:
    build: .
    container_name: telegram-bot
    env_file:
      - .env
    # Если нужно "пробросить" порт для webhook,
    # то указываем, например: "3000:3000".
    # В нашем случае используется long polling, так что доступ к порту не требуется,
    # но вот пример вам на будущее:
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
